version: "3.9"
services:
  bd:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_DB: "SpaceX"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "01233210"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U admin -d SpaceX'" ]
      interval: 5s
      timeout: 5s
      retries: 5


  app_rosatom:
    image: snesik/app_rosatom_v3
    depends_on:
     bd:
      condition: service_healthy
